In [1]:
import pandas as pd
import numpy as np

In [29]:
from goalguru.statsbombs_package.registry import load_model, load_scaler
from goalguru.statsbombs_package.data_processor import load_all_seasons_past_info

In [4]:
model = load_model()
model


Load latest model from local registry...

Load latest statsbomb model from disk...
✅ Model loaded from local disk


SGDClassifier(alpha=0.1, loss='modified_huber', max_iter=10000, penalty='l1')

In [7]:
coefs = model.coef_
coefs

array([[ 0.        ,  0.        , -0.03772994,  0.        , -0.03869322,
         0.        , -0.10298814,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.09914064,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.06104903,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.08247423,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.     

In [8]:
coefs.shape

(3, 36)

In [11]:
all_seasons = load_all_seasons_past_info()
all_seasons.columns

all_seasons.csv loaded locally


Index(['match_id', 'target', 'pass_completed_home_all_past',
       'pass_total_home_all_past', 'pass_precision_home_all_past',
       'shot_on_target_home_all_past', 'shot_goal_home_all_past',
       'shot_xg_home_all_past', 'shot_total_home_all_past',
       'shot_precision_home_all_past', 'shot_conversion_home_all_past',
       'pass_completed_home_last_10', 'pass_total_home_last_10',
       'pass_precision_home_last_10', 'shot_on_target_home_last_10',
       'shot_goal_home_last_10', 'shot_xg_home_last_10',
       'shot_total_home_last_10', 'shot_precision_home_last_10',
       'shot_conversion_home_last_10', 'pass_completed_away_all_past',
       'pass_total_away_all_past', 'pass_precision_away_all_past',
       'shot_on_target_away_all_past', 'shot_goal_away_all_past',
       'shot_xg_away_all_past', 'shot_total_away_all_past',
       'shot_precision_away_all_past', 'shot_conversion_away_all_past',
       'pass_completed_away_last_10', 'pass_total_away_last_10',
       'pass_prec

In [12]:
feats = all_seasons.columns[2:]
feats

Index(['pass_completed_home_all_past', 'pass_total_home_all_past',
       'pass_precision_home_all_past', 'shot_on_target_home_all_past',
       'shot_goal_home_all_past', 'shot_xg_home_all_past',
       'shot_total_home_all_past', 'shot_precision_home_all_past',
       'shot_conversion_home_all_past', 'pass_completed_home_last_10',
       'pass_total_home_last_10', 'pass_precision_home_last_10',
       'shot_on_target_home_last_10', 'shot_goal_home_last_10',
       'shot_xg_home_last_10', 'shot_total_home_last_10',
       'shot_precision_home_last_10', 'shot_conversion_home_last_10',
       'pass_completed_away_all_past', 'pass_total_away_all_past',
       'pass_precision_away_all_past', 'shot_on_target_away_all_past',
       'shot_goal_away_all_past', 'shot_xg_away_all_past',
       'shot_total_away_all_past', 'shot_precision_away_all_past',
       'shot_conversion_away_all_past', 'pass_completed_away_last_10',
       'pass_total_away_last_10', 'pass_precision_away_last_10',
       '

In [44]:
coefs_df = pd.DataFrame(coefs.T, columns=model.classes_, index=feats)
coefs_df

-1    0         1
pass_completed_home_all_past   0.000000  0.0  0.000000
pass_total_home_all_past       0.000000  0.0  0.134544
pass_precision_home_all_past  -0.037730  0.0  0.000000
shot_on_target_home_all_past   0.000000  0.0  0.000000
shot_goal_home_all_past       -0.038693  0.0  0.000000
shot_xg_home_all_past          0.000000  0.0  0.000000
shot_total_home_all_past      -0.102988  0.0  0.151678
shot_precision_home_all_past   0.000000  0.0  0.000000
shot_conversion_home_all_past  0.000000  0.0  0.000000
pass_completed_home_last_10    0.000000  0.0  0.000000
pass_total_home_last_10        0.000000  0.0  0.000000
pass_precision_home_last_10    0.000000  0.0  0.000000
shot_on_target_home_last_10    0.000000  0.0  0.000000
shot_goal_home_last_10         0.000000  0.0  0.000000
shot_xg_home_last_10           0.000000  0.0  0.000000
shot_total_home_last_10        0.000000  0.0  0.000000
shot_precision_home_last_10    0.000000  0.0  0.000000
shot_conversion_home_last_10   0.000000  0.0  0.000000
pass_completed_away_all_past   0.099141  0.0  0.000000
pass_total_away_all_past       0.000000  0.0 -0.089160
pass_precision_away_all_past   0.000000  0.0  0.000000
shot_on_target_away_all_past   0.000000  0.0  0.000000
shot_goal_away_all_past        0.000000  0.0  0.000000
shot_xg_away_all_past          0.000000  0.0  0.000000
shot_total_away_all_past       0.061049  0.0 -0.080756
shot_precision_away_all_past   0.000000  0.0  0.000000
shot_conversion_away_all_past  0.000000  0.0 -0.015658
pass_completed_away_last_10    0.000000  0.0  0.000000
pass_total_away_last_10        0.000000  0.0  0.000000
pass_precision_away_last_10    0.000000  0.0  0.000000
shot_on_target_away_last_10    0.000000  0.0  0.000000
shot_goal_away_last_10         0.082474  0.0  0.000000
shot_xg_away_last_10           0.000000  0.0  0.000000
shot_total_away_last_10        0.000000  0.0  0.000000
shot_precision_away_last_10    0.000000  0.0  0.000000
shot_conversion_away_last_10   0.000000  0.0  0.000000

In [45]:
coefs_df[(coefs_df > 0) | (coefs_df < 0)].dropna(how='all')

-1   0         1
pass_total_home_all_past            NaN NaN  0.134544
pass_precision_home_all_past  -0.037730 NaN       NaN
shot_goal_home_all_past       -0.038693 NaN       NaN
shot_total_home_all_past      -0.102988 NaN  0.151678
pass_completed_away_all_past   0.099141 NaN       NaN
pass_total_away_all_past            NaN NaN -0.089160
shot_total_away_all_past       0.061049 NaN -0.080756
shot_conversion_away_all_past       NaN NaN -0.015658
shot_goal_away_last_10         0.082474 NaN       NaN

In [42]:
all_seasons.iloc[0]

match_id                         3.890561e+06
target                          -1.000000e+00
pass_completed_home_all_past     3.299394e+02
pass_total_home_all_past         4.456970e+02
pass_precision_home_all_past     7.241602e-01
shot_on_target_home_all_past     6.757576e+00
shot_goal_home_all_past          1.151515e+00
shot_xg_home_all_past            1.213208e+00
shot_total_home_all_past         1.118182e+01
shot_precision_home_all_past     5.990345e-01
shot_conversion_home_all_past    1.086730e-01
pass_completed_home_last_10      3.688000e+02
pass_total_home_last_10          4.784000e+02
pass_precision_home_last_10      7.603091e-01
shot_on_target_home_last_10      8.400000e+00
shot_goal_home_last_10           1.500000e+00
shot_xg_home_last_10             1.588514e+00
shot_total_home_last_10          1.300000e+01
shot_precision_home_last_10      6.589929e-01
shot_conversion_home_last_10     1.275523e-01
pass_completed_away_all_past     3.866364e+02
pass_total_away_all_past         4

In [26]:
np.exp(model.intercept_)

array([0.68470091, 0.61159412, 0.87515618])

In [34]:
scaler = load_scaler()
default_prob = model.predict_proba(scaler.transform(np.zeros((1,36))))
default_prob


Load latest scaler from local registry...

Load latest scaler from disk...
✅ Scaler loaded from local disk


/home/javier/.pyenv/versions/3.10.6/envs/goalguru/lib/python3.10/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but RobustScaler was fitted with feature names
  warnings.warn(


array([[0.44508401, 0.28508954, 0.26982645]])

In [41]:
np.around(default_prob*100, 2)

array([[44.51, 28.51, 26.98]])

In [47]:
all_seasons['target'].value_counts(normalize=True)

 1    0.444788
-1    0.313900
 0    0.241313
Name: target, dtype: float64

In [50]:
all_seasons.iloc[-1,2:]

pass_completed_home_all_past    NaN
pass_total_home_all_past        NaN
pass_precision_home_all_past    NaN
shot_on_target_home_all_past    NaN
shot_goal_home_all_past         NaN
shot_xg_home_all_past           NaN
shot_total_home_all_past        NaN
shot_precision_home_all_past    NaN
shot_conversion_home_all_past   NaN
pass_completed_home_last_10     NaN
pass_total_home_last_10         NaN
pass_precision_home_last_10     NaN
shot_on_target_home_last_10     NaN
shot_goal_home_last_10          NaN
shot_xg_home_last_10            NaN
shot_total_home_last_10         NaN
shot_precision_home_last_10     NaN
shot_conversion_home_last_10    NaN
pass_completed_away_all_past    NaN
pass_total_away_all_past        NaN
pass_precision_away_all_past    NaN
shot_on_target_away_all_past    NaN
shot_goal_away_all_past         NaN
shot_xg_away_all_past           NaN
shot_total_away_all_past        NaN
shot_precision_away_all_past    NaN
shot_conversion_away_all_past   NaN
pass_completed_away_last_10 

In [55]:
model.predict_proba(scaler.transform(all_seasons.iloc[-1,2:].fillna(0).to_numpy().reshape(1, -1)))

/home/javier/.pyenv/versions/3.10.6/envs/goalguru/lib/python3.10/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but RobustScaler was fitted with feature names
  warnings.warn(


array([[0.44508401, 0.28508954, 0.26982645]])